language: python
dist: trusty
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - nightly
matrix:
  allow_failures:
    - python: nightly
  fast_finish: true
before_install:
  - pip install --upgrade pip   
install:
  - pip install .[test]
  - pip install .
script:
    # https://github.com/PyCQA/pylint/issues/1113
  - if [ $TRAVIS_PYTHON_VERSION != 3.6 ] && [ $TRAVIS_PYTHON_VERSION != nightly ]; then pylint --rcfile .pylintrc -E rtv/; fi
  - coverage run -m py.test -v
after_success:
  - coveralls
